import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";

export const getStaticProps: GetStaticProps<
  Awaited<ReturnType<typeof serverSideTranslations>>,
  { locale: string }
> = async ({ locale }) => {
  const { _nextI18Next } = await serverSideTranslations(locale!);

  return {
    props: {
      _nextI18Next,
    },
  };
};

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>First Aid Decor Kit</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="min-h-screen flex flex-col justify-start items-center">
        <h1 className="card w-full max-w-360">Привіт</h1>
      </main>
    </div>
  );
};

export default Home;
