import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import { Fragment } from "react";
import { About, Intro, Services } from "components/landing";
import { getServices } from "constants/services";

type Props = {
  services: Array<TService>;
};

export const getStaticProps: GetStaticProps<Props> = async ({ locale }) => {
  const { _nextI18Next } = await serverSideTranslations(locale!);

  return {
    props: {
      _nextI18Next,
      services: getServices(),
    },
  };
};

const Home: NextPage<Props> = ({ services }) => {
  return (
    <Fragment>
      <Head>
        <title>First Aid Decor</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="w-full flex flex-col justify-center items-center">
        <Intro />
        <About />
        <Services services={services} />
      </main>
    </Fragment>
  );
};

export default Home;
