import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import { Fragment } from "react";
import { About, Intro, Services } from "components/landing";

const description = `Lorem ipsum dolor sit amet consectetur adipisicing elit. Iste
molestiae sunt, porro totam reiciendis repellat nostrum tempora itaque
nihil vel rerum. Nostrum, rem id officia voluptatem ducimus quibusdam
eaque in. Repellat magnam maxime inventore vel ab, nihil commodi nam
rerum necessitatibus quaerat, voluptates earum nobis id? Accusamus
veritatis, sed nobis id non exercitationem officia quis, reprehenderit
nesciunt aliquam hic nam.`;

const services: Array<TService> = [
  {
    title: "Експрес-консультація з декорування",
    description:
      "Час щось змінити! Отримайте швидкий аналіз інтер'єру, виявіть його сильні та слабкі риси, отримайте рекомендації щодо придбання декору чи меблів.",
    imgSrc: "/images/articles/express-decor.jpeg",
    link: "/service/consulting",
  },
  {
    title: "Декорування Вашої оселі під ключ",
    description:
      "Від ідеї до втілення працюємо пліч-о-пліч для досягнення найкращого результату. Кожен проект індивідуальний, це може бути окрема кімната або увесь будинок.",
    imgSrc: "/images/articles/article-img-2.jpeg",
    link: "/service/house-decoration",
  },
  {
    title: "Підготовка житла до оренди чи продажу",
    description:
      "Зробіть Ваше оголошення помітним! Вартість задекорованної та охайної оселі завжди вища, бо платять не за квадратні метри, а за відчуття.",
    imgSrc: "/images/articles/property-preparation.jpeg",
    link: "/service/property-preparation",
  },
  {
    title: "Святкове декорування та сервіровка",
    description:
      "Нехай свято буде незабутнім! Щоб зробити красиву сервіровку або прикрасити увесь дім квітами, приводи не потрібні, лише декоратор.",
    imgSrc: "/images/articles/article-img-3.jpeg",
    link: "/service/holiday-decoration",
  },
  {
    title: "Створення столового гардеробу",
    description,
    imgSrc: "/images/articles/dining-room-wardrobe.jpeg",
    link: "/service/dining-room-wardrobe",
  },
  {
    title: "First Aid Decor Kit",
    description:
      "Готові набори для самостійного декорування оселі та сервіровок. Кожен набір унікальний, тож не зволікайте та встигніть придбати той, що більше всього сподобався!",
    imgSrc: "/images/articles/article-img-6.jpeg",
    link: "/services/first-aid-decor-kit",
  },
];

type Props = Awaited<ReturnType<typeof serverSideTranslations>>;

export const getStaticProps: GetStaticProps<Props> = async ({ locale }) => {
  const { _nextI18Next } = await serverSideTranslations(locale!);

  return {
    props: {
      _nextI18Next,
    },
  };
};

const Home: NextPage<Props> = () => {
  return (
    <Fragment>
      <Head>
        <title>First Aid Decor Kit</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="w-full flex flex-col justify-center items-center">
        <Intro />
        <About />
        <Services services={services} />
      </main>
    </Fragment>
  );
};

export default Home;
